name: Terraform Pull Request Workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  Terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1.0.1

    - name: Terraform Init
      run: terraform init 
          -backend-config="bucket=pmp-terraform-state-develop" 
          -backend-config="key=ccs-pmp-infra-idam" 
          -backend-config="region=eu-west-2" 
          -backend-config="dynamodb_table=pmp_terraform_state_lock-develop" 
          -backend-config="encrypt=true"
      env:
        GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: '.'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Checks that all Terraform configuration files adhere to a canonical format
    # - name: Terraform Format
    #   run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var 'env_var=develop' -var 'callbackurl=-dev'
      env:
        GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: '.'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}